### ISSUE TITLE
Inquiry

### ISSUE THREAD

**Issue by Ogujiuba-Henry** [dtsiken/Advance-Keylogger#1]
What is the exact command for compiling the keylogger to .exe using nuitka?

My keylogger executable won't send the email

**Comment by dtsiken** [comment]
When you compiling it use this command
What you need first is:
mingw64 installed onto your computer and proceed to compiling

Use this command
python -m nuitka --mingw64 yourpythonfile.py --standalone --onefile

**Comment by Ogujiuba-Henry** [comment]
1.) I used the command you specified without having mingw64 installed and the script still compiled. Could that be a problem?

2.) There's no mingw64, just mingw-w64.
Should I use that instead?

I'm sorry, this will be the final questions
